apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: brxm-repo-maintainer-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: brxm-repo-maintainer
roleRef:
  kind: Role
  name: brxm-repo-maintainer
  apiGroup: rbac.authorization.k8s.io